"""empty message

Revision ID: 0bab8ff14ece
Revises: 
Create Date: 2022-08-03 22:32:35.622523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bab8ff14ece'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.alter_column('artist', 'id',
               existing_type=sa.BIGINT(),
               nullable=False,
               autoincrement=True)
    op.alter_column('artist', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('artist', 'city',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('artist', 'state',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('artist', 'phone',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('artist', 'genres',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_foreign_key(None, 'show', 'artist', ['artist_id'], ['id'])
    op.create_foreign_key(None, 'show', 'venue', ['venue_id'], ['id'])
    op.alter_column('venue', 'id',
               existing_type=sa.BIGINT(),
               nullable=False,
               autoincrement=True)
    op.alter_column('venue', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('venue', 'address',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('venue', 'city',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('venue', 'state',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('venue', 'phone',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('venue', 'genres',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_unique_constraint(None, 'venue', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venue', type_='unique')
    op.alter_column('venue', 'genres',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('venue', 'phone',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('venue', 'state',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('venue', 'city',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('venue', 'address',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('venue', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('venue', 'id',
               existing_type=sa.BIGINT(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.alter_column('artist', 'genres',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('artist', 'phone',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('artist', 'state',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('artist', 'city',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('artist', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('artist', 'id',
               existing_type=sa.BIGINT(),
               nullable=True,
               autoincrement=True)
    op.drop_table('user')
    # ### end Alembic commands ###
